In [1]:
import numpy as np
import pandas as pd

In [2]:
matches = pd.read_csv('matches.csv')
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [3]:
def Bowlingteam(row):
    if (row['Team1'] == row['TossWinner']):
        if row['TossDecision'] == 'bat':
            return row['Team1']
        else:
            return row['Team2']
    else:
        if row['TossDecision'] == 'bat':
            return row['Team2']
        else:
            return row['Team1']

In [4]:
matches['BowlingTeam'] = matches.apply(Bowlingteam,axis=1)

In [5]:
matches

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,BowlingTeam
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,Rajasthan Royals
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,Royal Challengers Bangalore
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,Royal Challengers Bangalore
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,Rajasthan Royals
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,Sunrisers Hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,Deccan Chargers
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,Mumbai Indians
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,Rajasthan Royals
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,Chennai Super Kings
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,Kolkata Knight Riders

In [6]:
delivery = pd.read_csv('deliveries.csv')
delivery.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [7]:
total_score_df = delivery.groupby(['ID','innings']).sum()['total_run'].reset_index()

In [8]:
total_score_df

           ID  innings  total_run
0      335982        1        222
1      335982        2         82
2      335983        1        240
3      335983        2        207
4      335984        1        129
...       ...      ...        ...
1923  1312198        2        193
1924  1312199        1        157
1925  1312199        2        161
1926  1312200        1        130
1927  1312200        2        133

[1928 rows x 3 columns]

In [9]:
total_score_df = total_score_df[total_score_df['innings']==1]

In [10]:
total_score_df

           ID  innings  total_run
0      335982        1        222
2      335983        1        240
4      335984        1        129
6      335985        1        165
8      335986        1        110
...       ...      ...        ...
1918  1304116        1        157
1920  1312197        1        188
1922  1312198        1        207
1924  1312199        1        157
1926  1312200        1        130

[950 rows x 3 columns]

In [11]:
match_df = matches.merge(total_score_df[['ID','total_run']],left_on='ID',right_on='ID')

In [12]:
match_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,BowlingTeam,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,Rajasthan Royals,130
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,Royal Challengers Bangalore,157
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,Royal Challengers Bangalore,207
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,Rajasthan Royals,188
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,Sunrisers Hyderabad,157

In [13]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [14]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Chennai Super Kings',
    'Kolkata Knight Riders',
    'Punjab Kings',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants',
    'Rajasthan Royals'
]

In [15]:
match_df['Team1'] = match_df['Team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['Team2'] = match_df['Team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['Team1'] = match_df['Team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['Team2'] = match_df['Team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [16]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Kings XI Punjab',
       'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Kochi Tuskers Kerala'],
      dtype=object)

In [17]:
match_df['Team1'] = match_df['Team1'][match_df['Team1'].isin(teams)]
match_df['Team2'] = match_df['Team2'][match_df['Team2'].isin(teams)]

In [18]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', nan], dtype=object)

In [19]:
match_df.shape

(950, 22)

In [20]:
match_df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,BowlingTeam,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,Rajasthan Royals,130
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,Royal Challengers Bangalore,157
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,Royal Challengers Bangalore,207
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,Rajasthan Royals,188
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,Sunrisers Hyderabad,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Sunrisers Hyderabad,Eden Gardens,Deccan Chargers,bat,...,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,Deccan Chargers,110
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,Mumbai Indians,165
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Capitals,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,Rajasthan Royals,129
948,335983,Chandigarh,2008-04-19,2007/08,2,NaN,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,Chennai Super Kings,240
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,Kolkata Knight Riders,222

In [21]:
match_df = match_df[match_df['method'].isnull()]

In [22]:
match_df.shape

(931, 22)

In [23]:
match_df = match_df[['ID','Venue','WinningTeam','BowlingTeam','total_run']]

In [24]:
match_df.head()

,ID,Venue,WinningTeam,BowlingTeam,total_run
0,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130
1,1312199,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,Royal Challengers Bangalore,157
2,1312198,"Eden Gardens, Kolkata",Royal Challengers Bangalore,Royal Challengers Bangalore,207
3,1312197,"Eden Gardens, Kolkata",Gujarat Titans,Rajasthan Royals,188
4,1304116,"Wankhede Stadium, Mumbai",Punjab Kings,Sunrisers Hyderabad,157

In [25]:
delivery_df = match_df.merge(delivery,on='ID')

In [26]:
delivery_df.head()

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,extra_type,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,1,0,1,YBK Jaiswal,Mohammed Shami,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,1,0,2,YBK Jaiswal,Mohammed Shami,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,1,0,3,JC Buttler,Mohammed Shami,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,1,0,4,YBK Jaiswal,Mohammed Shami,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,1,0,5,YBK Jaiswal,Mohammed Shami,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [27]:
delivery_df = delivery_df[delivery_df['innings']== 2]

In [28]:
delivery_df.shape

(107749, 21)

In [29]:
delivery_df['total_run_y'] = pd.to_numeric(delivery_df['total_run_y'], errors='coerce')
delivery_df['current_score'] = delivery_df.groupby('ID')['total_run_y'].cumsum()

In [30]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,current_score
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,0
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,0
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,1
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,1
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,80
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,82
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,82

In [31]:
delivery_df['runs_left'] = delivery_df['total_run_x']-delivery_df['current_score']

In [32]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,current_score,runs_left
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,0,130
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,0,130
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,1,129
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,1,129
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,80,142
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,82,140
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,82,140

In [33]:
delivery_df['balls_left'] = 120 - (delivery_df['overs']*6 + delivery_df['ballnumber'])

In [34]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,current_score,runs_left,balls_left
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,0,130,119
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,0,130,118
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,1,0,0,NaN,NaN,NaN,Gujarat Titans,1,129,117
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,1,129,116
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,1,129,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,80,142,31
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,30
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,29
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,82,140,29
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,82,140,28

In [35]:
delivery_df['wickets_left'] = 10 - delivery_df.groupby('ID')['isWicketDelivery'].cumsum()

In [36]:
delivery_df['wickets_left'].unique()

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0], dtype=int64)

In [37]:
delivery_df['crr'] = (delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

In [38]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,current_score,runs_left,balls_left,wickets_left,crr
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,0,NaN,NaN,NaN,Gujarat Titans,0,130,119,10,0.000000
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,0,NaN,NaN,NaN,Gujarat Titans,0,130,118,10,0.000000
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,0,NaN,NaN,NaN,Gujarat Titans,1,129,117,10,2.000000
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,0,NaN,NaN,NaN,Gujarat Titans,1,129,116,10,1.500000
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,0,NaN,NaN,NaN,Gujarat Titans,1,129,115,10,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,80,142,31,1,5.393258
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,30,1,5.400000
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,29,1,5.340659
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,0,NaN,NaN,NaN,Royal Challengers Bangalore,82,140,29,1,5.406593
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,82,140,28,0,5.347826

In [39]:
delivery_df['rrr'] = (delivery_df['runs_left']*6)/(delivery_df['balls_left'])

In [40]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,player_out,kind,fielders_involved,BattingTeam,current_score,runs_left,balls_left,wickets_left,crr,rrr
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,NaN,NaN,NaN,Gujarat Titans,0,130,119,10,0.000000,6.554622
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,NaN,NaN,NaN,Gujarat Titans,0,130,118,10,0.000000,6.610169
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,NaN,NaN,NaN,Gujarat Titans,1,129,117,10,2.000000,6.615385
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,NaN,NaN,NaN,Gujarat Titans,1,129,116,10,1.500000,6.672414
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,NaN,NaN,NaN,Gujarat Titans,1,129,115,10,1.200000,6.730435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,NaN,NaN,NaN,Royal Challengers Bangalore,80,142,31,1,5.393258,27.483871
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,30,1,5.400000,28.200000
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,NaN,NaN,NaN,Royal Challengers Bangalore,81,141,29,1,5.340659,29.172414
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,NaN,NaN,NaN,Royal Challengers Bangalore,82,140,29,1,5.406593,28.965517
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,82,140,28,0,5.347826,30.000000

In [41]:
def result(row):
    return 1 if row['BattingTeam'] == row['WinningTeam'] else 0

In [42]:
delivery_df['result'] = delivery_df.apply(result,axis=1)

In [43]:
delivery_df

,ID,Venue,WinningTeam,BowlingTeam,total_run_x,innings,overs,ballnumber,batter,bowler,...,kind,fielders_involved,BattingTeam,current_score,runs_left,balls_left,wickets_left,crr,rrr,result
120,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,1,WP Saha,TA Boult,...,NaN,NaN,Gujarat Titans,0,130,119,10,0.000000,6.554622,1
121,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,2,WP Saha,TA Boult,...,NaN,NaN,Gujarat Titans,0,130,118,10,0.000000,6.610169,1
122,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,3,WP Saha,TA Boult,...,NaN,NaN,Gujarat Titans,1,129,117,10,2.000000,6.615385,1
123,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,4,Shubman Gill,TA Boult,...,NaN,NaN,Gujarat Titans,1,129,116,10,1.500000,6.672414,1
124,1312200,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,130,2,0,5,Shubman Gill,TA Boult,...,NaN,NaN,Gujarat Titans,1,129,115,10,1.200000,6.730435,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,5,P Kumar,I Sharma,...,NaN,NaN,Royal Challengers Bangalore,80,142,31,1,5.393258,27.483871,0
222742,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,6,SB Joshi,I Sharma,...,NaN,NaN,Royal Challengers Bangalore,81,141,30,1,5.400000,28.200000,0
222743,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,14,7,P Kumar,I Sharma,...,NaN,NaN,Royal Challengers Bangalore,81,141,29,1,5.340659,29.172414,0
222744,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,1,SB Joshi,LR Shukla,...,NaN,NaN,Royal Challengers Bangalore,82,140,29,1,5.406593,28.965517,0
222745,335982,M Chinnaswamy Stadium,Kolkata Knight Riders,Kolkata Knight Riders,222,2,15,2,SB Joshi,LR Shukla,...,caught,BB McCullum,Royal Challengers Bangalore,82,140,28,0,5.347826,30.000000,0

In [44]:
final_df = delivery_df[['ID','BattingTeam','BowlingTeam','Venue','runs_left','balls_left','wickets_left','total_run_x','crr','rrr','result']]

In [45]:
final_df

,ID,BattingTeam,BowlingTeam,Venue,runs_left,balls_left,wickets_left,total_run_x,crr,rrr,result
120,1312200,Gujarat Titans,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",130,119,10,130,0.000000,6.554622,1
121,1312200,Gujarat Titans,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",130,118,10,130,0.000000,6.610169,1
122,1312200,Gujarat Titans,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",129,117,10,130,2.000000,6.615385,1
123,1312200,Gujarat Titans,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",129,116,10,130,1.500000,6.672414,1
124,1312200,Gujarat Titans,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",129,115,10,130,1.200000,6.730435,1
...,...,...,...,...,...,...,...,...,...,...,...
222741,335982,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,142,31,1,222,5.393258,27.483871,0
222742,335982,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,141,30,1,222,5.400000,28.200000,0
222743,335982,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,141,29,1,222,5.340659,29.172414,0
222744,335982,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,140,29,1,222,5.406593,28.965517,0
222745,335982,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,140,28,0,222,5.347826,30.000000,0

In [46]:
final_df = final_df.sample(final_df.shape[0])

In [47]:
final_df.dropna(inplace=True)

In [48]:
final_df = final_df[final_df['balls_left']!=0]

In [49]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

C:\Users\91918\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [50]:
X_train

,ID,BattingTeam,BowlingTeam,Venue,runs_left,balls_left,wickets_left,total_run_x,crr,rrr
72525,1136572,Chennai Super Kings,Kings XI Punjab,Punjab Cricket Association IS Bindra Stadium,59,19,6,197,8.198020,18.631579
170143,501250,Pune Warriors,Deccan Chargers,"Rajiv Gandhi International Stadium, Uppal",120,110,10,136,9.600000,6.545455
101347,980907,Sunrisers Hyderabad,Royal Challengers Bangalore,M Chinnaswamy Stadium,126,50,5,227,8.657143,15.120000
85340,1082605,Kings XI Punjab,Delhi Daredevils,Feroz Shah Kotla,60,13,4,188,7.177570,27.692308
17907,1304047,Kolkata Knight Riders,Chennai Super Kings,"Wankhede Stadium, Mumbai",6,13,6,131,7.009346,2.769231
...,...,...,...,...,...,...,...,...,...,...
5933,1304096,Sunrisers Hyderabad,Delhi Capitals,"Brabourne Stadium, Mumbai",163,72,7,207,5.500000,13.583333
153728,548358,Rajasthan Royals,Pune Warriors,Subrata Roy Sahara Stadium,13,29,7,125,7.384615,2.689655
183823,419158,Kolkata Knight Riders,Rajasthan Royals,Eden Gardens,60,55,8,132,6.646154,6.545455
139219,598032,Rajasthan Royals,Sunrisers Hyderabad,Sawai Mansingh Stadium,131,98,9,144,3.545455,8.020408
125272,729315,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,16,13,6,152,7.626168,7.384615

In [51]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([('trf',OneHotEncoder(sparse=False,drop='first'),['BattingTeam','BowlingTeam','Venue'])
                        ]
                        ,remainder='passthrough')

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [53]:
pipe = Pipeline(steps=[
    ('step1', trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [54]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['BattingTeam', 'BowlingTeam',
                                                   'Venue'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [55]:
y_pred = pipe.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.763317191283293

In [57]:
pipe.predict_proba(X_test)[10]

array([0.32368819, 0.67631181])

In [58]:
'''def match_progression(x_df,match_id,pipe):
    match = x_df[x_df['ID'] == match_id]
    match = match[(match['ballnumber'] == 6)]
    temp_df = match[['BattingTeam','BowlingTeam','Venue','runs_left','balls_left','wickets_left','total_run_x','crr','rrr']].dropna()
    temp_df = temp_df[temp_df['balls_left'] != 0]
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0]*100,1)
    temp_df['win'] = np.round(result.T[1]*100,1)
    temp_df['end_of_over'] = range(1,temp_df.shape[0]+1)
    
    target = temp_df['total_run_x'].values[0]
    runs = list(temp_df['runs_left'].values)
    new_runs = runs[:]
    runs.insert(0,target)
    temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)
    wickets = list(temp_df['wickets_left'].values)
    new_wickets = wickets[:]
    new_wickets.insert(0,10)
    wickets.append(0)
    w = np.array(wickets)
    nw = np.array(new_wickets)
    temp_df['wickets_in_over'] = (nw - w)[0:temp_df.shape[0]]
    
    print("Target-",target)
    temp_df = temp_df[['end_of_over','runs_after_over','wickets_in_over','lose','win']]
    return temp_df,target'''

'def match_progression(x_df,match_id,pipe):\n    match = x_df[x_df[\'ID\'] == match_id]\n    match = match[(match[\'ballnumber\'] == 6)]\n    temp_df = match[[\'BattingTeam\',\'BowlingTeam\',\'Venue\',\'runs_left\',\'balls_left\',\'wickets_left\',\'total_run_x\',\'crr\',\'rrr\']].dropna()\n    temp_df = temp_df[temp_df[\'balls_left\'] != 0]\n    result = pipe.predict_proba(temp_df)\n    temp_df[\'lose\'] = np.round(result.T[0]*100,1)\n    temp_df[\'win\'] = np.round(result.T[1]*100,1)\n    temp_df[\'end_of_over\'] = range(1,temp_df.shape[0]+1)\n    \n    target = temp_df[\'total_run_x\'].values[0]\n    runs = list(temp_df[\'runs_left\'].values)\n    new_runs = runs[:]\n    runs.insert(0,target)\n    temp_df[\'runs_after_over\'] = np.array(runs)[:-1] - np.array(new_runs)\n    wickets = list(temp_df[\'wickets_left\'].values)\n    new_wickets = wickets[:]\n    new_wickets.insert(0,10)\n    wickets.append(0)\n    w = np.array(wickets)\n    nw = np.array(new_wickets)\n    temp_df[\'wickets_in_over\'] = (nw - w)[0:temp_df.shape[0]]\n    \n    print("Target-",target)\n    temp_df = temp_df[[\'end_of_over\',\'runs_after_over\',\'wickets_in_over\',\'lose\',\'win\']]\n    return temp_df,target'

In [59]:
def match_progression(x_df, match_id, pipe):
    match = x_df[x_df['ID'] == match_id]
    temp_df = match[['BattingTeam', 'BowlingTeam', 'Venue', 'runs_left', 'balls_left', 'wickets_left', 'total_run_x', 'crr', 'rrr']].dropna()
    if temp_df.empty:
        print("No data available for match_id:", match_id)
        return None, None
    
    temp_df = temp_df[temp_df['balls_left'] != 0]
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0] * 100, 1)
    temp_df['win'] = np.round(result.T[1] * 100, 1)
    
    return temp_df, result

In [60]:
temp_df, result = match_progression(delivery_df, 598065, pipe)

if temp_df is not None:
    print(temp_df)

ValueError: X has 9 features, but ColumnTransformer is expecting 10 features as input.